name: symb_expl
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gxx_linux-64>=13.1.0
  - gcc_linux-64>=13.1.0
  - swig>=4.1.1
  - pip>=23.1.2
  - pip:
    - openml==0.12.2
    - smac==v2.0.0
    - configspace==0.6.1
    - xgboost==1.3.1
    - interruptingcow==0.8
    - gplearn>=0.4.2
    - sympy>=1.12
    - dill>=0.3.6
    - loguru>=0.7.0
    - tqdm>=4.65.0
    - matplotlib>=3.7.2
    - seaborn>=0.12.2
    - pandas>=2.0.3