name: symb_expl
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gxx_linux-64
  - gcc_linux-64
  - swig
  - pip
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - gplearn
  - sympy
  - black
  - dill
  - loguru
  - tqdm
  - openml
  - pip:
    - smac==v2.0.0
    - configspace==0.6.1
    - xgboost==1.3.1
    - interruptingcow